# ********************************
# Transmitter targets
# ********************************

[env:Aeronetix_ESP32_LR1121_TX_via_ETX]
extends = env:Unified_ESP32_LR1121_TX_via_ETX
board_config = aeronetix.tx_dual.lr1121_450_700_v2

[env:Aeronetix_ESP32_LR1121_TX_via_UART]
extends = env:Unified_ESP32_LR1121_TX_via_UART
board_config = aeronetix.tx_dual.lr1121_450_700_v2

[env:Aeronetix_ESP32_LR1121_TX_via_WIFI]
extends = env:Unified_ESP32_LR1121_TX_via_WIFI
board_config = aeronetix.tx_dual.lr1121_450_700_v2

[env:Aeronetix_ESP32_LR1121_5W_150_450_TX_via_ETX]
extends = env:Unified_ESP32_LR1121_TX_via_ETX
board_config = aeronetix.tx_dual.lr1121_5w_150_450_v1

[env:Aeronetix_ESP32_LR1121_5W_150_450_TX_via_UART]
extends = env:Unified_ESP32_LR1121_TX_via_UART
board_config = aeronetix.tx_dual.lr1121_5w_150_450_v1

[env:Aeronetix_ESP32_LR1121_5W_150_450_TX_via_WIFI]
extends = env:Unified_ESP32_LR1121_TX_via_WIFI
board_config = aeronetix.tx_dual.lr1121_5w_150_450_v1

[env:Aeronetix_ESP32_LR1121_5W_450_750_TX_via_ETX]
extends = env:Unified_ESP32_LR1121_TX_via_ETX
board_config = aeronetix.tx_dual.lr1121_5w_450_750_v1

[env:Aeronetix_ESP32_LR1121_5W_450_750_TX_via_UART]
extends = env:Unified_ESP32_LR1121_TX_via_UART
board_config = aeronetix.tx_dual.lr1121_5w_450_750_v1

[env:Aeronetix_ESP32_LR1121_5W_TX_via_UART]
extends = env:Unified_ESP32_LR1121_TX_via_UART
board_config = aeronetix.tx_dual.lr1121_5w_v1

[env:Aeronetix_ESP32_LR1121_5W_450_750_TX_via_WIFI]
extends = env:Unified_ESP32_LR1121_TX_via_WIFI
board_config = aeronetix.tx_dual.lr1121_5w_450_750_v1